### ISSUE TITLE
Move/Perk Equality

### ISSUE THREAD

**Issue by alexvanyo** [EtherBots/ETHERBOTS-Bug-Bounty#1]
In the `_applyBonusTree` function in `StageBattle.sol`, the perk bonus is applied twice for the DODGE move/ BODY perk and the TURRET move/TURRET perk, where it is only applied once for to the other two moves and their corresponding perks (see lines 502-503 and 542-543). The whitepaper states that there should be a fixed bonus _**f**_ for each active perk, so is this intentional?

**Comment by EtherBots** [comment]
Addressed in your later change.
