### ISSUE TITLE
A method to lock bots or force attackers to win

### ISSUE THREAD

**Issue by alexvanyo** [EtherBots/ETHERBOTS-Bug-Bounty#10]
This is partly related to #3 (and I found this via that issue), but this is a separate and more serious problem.

Currently, `attack` doesn't validate the type or count of the attacker's parts; it only checks that the attack owns them all, if any (`ownsAll` will return true even if the attacker is attacking with 0 parts). Here are some implications:

- The attacker doesn't need 1 of each of the 4 types of parts. This clearly breaks the rock-paper-scissors style of the game, and also allows the attacker to send one part 4 times (since this isn't checked either)

- If the attacker sends less than 4 parts, then `defenderRevealMoves` will always cause an array out of bounds exception, specifically in `_executeMoves` when `attackerParts` is constructed (line 651). Because of this, the defender cannot win, and they will either have to call `cancelBattle` or an attacker can call `claimTimeVictory`.

- If the attacker sends 0 parts or doesn't choose their moves advantageously, then `cancelBattle` and `claimTimeVictory` will also cause an array out of bound exceptions in `_forfeitBattle` -> `_allocateExperience` -> `exps[moves[i]]` (line 856). This causes all the defender bot to be locked up, as the duels can't be resolved and the bot transferred back.

- If the attacker sends 1-3 parts and does choose their moves advantageously (sending only a DEFENCE and MELEE part, and only DEFENDing, for instance), then `cancelBattle` and `claimTimeVictory` will not cause an exception on line 856, and the rest of the experience code will not crash. This means that all attackers can be forced to win.

- If the attacker sends more than 4 parts, then most of the battle logic works properly, although the experience scaling is not correct and additional legitimate attackers will likely not be able to attack because `_canAttack` will cause an out of bounds exception.

Fix:

The attacker parts should also be validated like they are for the defender:
```
// check parts //defence1 melee2 body3 turret4
uint8[4] memory types = [1, 2, 3, 4];
require(_base.hasPartTypes(partIds, types));
```

**Comment by EtherBots** [comment]
Thanks for your work @alexvanyo, this is an important bug (and simply solved, thankfully). We've decided to award you 500 points for the sum of your work so far. Please respond with your public address/e-mail us if you don't wish it to be public (support@etherbots.io).

**Comment by alexvanyo** [comment]
You are welcome and thank you, my public address is below:
0xcb109C6467fdFa47080C1975C5D12d5d783abE86

**Comment by jamesanthonyferguson** [comment]
We have transferred you 0.6Eth which is worth $503USD at the time of the transaction.
https://etherscan.io/tx/0xa139445415a4ad2a03b52a2a00ef868fd3da9fd1bf5523e30a80464785c6c8e7

Keep up the great work!
