### ISSUE TITLE
Optimized version of `_applyBonusTree`

### ISSUE THREAD

**Issue by alexvanyo** [EtherBots/ETHERBOTS-Bug-Bounty#13]
The following is an optimized version of the `_applyBonusTree` function, which takes advantage of the binary tree structure of the perk tree. The PT constants are no longer necessary with this version, and the helper functions `getMoveType`, `hasPerk`, and `_applyPerkBonus` can all easily be made inline and removed. This version also fixes #1 and #2.

```
bytes4 constant moveToPT = 0x06050304;
bytes4 constant elementToPT = 0x05060403;
uint8 constant PRESTIGE_BONUS = 1;

function _applyBonusTree(uint8 move, EtherbotsBase.Part[4] parts, uint8[32] tree) internal pure returns (uint8 bonus) {
    uint8 prestige = tree[PT_PRESTIGE_INDEX];
    
    uint8 active = 0;
    uint8 level2 = uint8(moveToPT[move]);
    uint8 level1 = (level2 - 1) / 2;
    
    if (tree[level1] > 0) {
        active++;
        if (tree[level2] > 0) {
            active++;
            
            uint8 level4 = level2 * 4 + uint8(elementToPT[parts[move].element]);
            uint8 level3 = (level4 - 1) / 2;
            
            if (tree[level3] > 0) {
                active++;
                if (tree[level4] > 0) {
                    active++;
                }
            }
        }
    }

    bonus = active * (PERK_BONUS + (prestige * PRESTIGE_BONUS));
}
```

**Comment by RobbieFerguson** [comment]
This looks excellent, testing it now.

**Comment by EtherBots** [comment]
Hey, we've implemented this on the testnet. We'll see how the savings go gas-wise to fine tune the points but this is definitely deserving of some. Thanks!

**Comment by EtherBots** [comment]
We ended up using this (apart from a slight indexing bug! :P) so thank you for your hard work. Will discuss appropriate additional bounty for this with the team.
