### ISSUE TITLE
Multiple charges for reward crate

### ISSUE THREAD

**Issue by tatertot478** [EtherBots/ETHERBOTS-Bug-Bounty#19]
<img width="749" alt="screen shot 2018-02-25 at 11 01 33 am" src="https://user-images.githubusercontent.com/35508474/36651256-d72a1e3e-1a5c-11e8-83cc-7d2e987916e5.png">
<img width="964" alt="screen shot 2018-02-25 at 11 01 52 am" src="https://user-images.githubusercontent.com/35508474/36651257-d73e845a-1a5c-11e8-9438-ca835b836ea1.png">

I'm not exactly sure if this qualifies as a bug, as I don't believe I received more than the initial crate reward, but the "claim reward" button was continuously clickable, and I was able to queue up a dozen transactions. It was only after I exited the browser and reloaded it that the button disappeared

**Comment by EtherBots** [comment]
Web3 issue, not solidity, but thanks for bringing it to our attention @tatertot478!
