### ISSUE TITLE
Mech overrides Android

### ISSUE THREAD

**Issue by alexvanyo** [EtherBots/ETHERBOTS-Bug-Bounty#2]
In the `_applyBonusTree` function in `StageBattle.sol`, the `else if`'s prevent Android perks from being considered if the user also has the Mech perk. For eaxmple, if the user has filled out the perk tree entirely, then it is impossible to get any perk bonuses for fire or water type moves, because the Mech clause will only check to see if the move was electric or steel.

I believe this could be fixed by swapping the order of the conditionals, similar to how the code handles offense/defense and the different moves.

**Comment by EtherBots** [comment]
This looks to be right at a first glance. Will go over with the team and get back to you.

**Comment by EtherBots** [comment]
Addressed in your later change.
