### ISSUE TITLE
Battle screen improvements

### ISSUE THREAD

**Issue by lopanism** [EtherBots/ETHERBOTS-Bug-Bounty#20]
1) Impossible to see artwork in the top/center of the screen, because it overlaps. 

2) See some of the suggestions for battle screen UI. It would be great to add: 
— Information about the total moves won by each party
— Overall battle indicator - how close is the bot to winning or losing
— Total damage inflicted, as moves won don't necessarily determine the outcome.

I can provide a more well thought-through mockup if needed. 

![screenshot 2018-02-26 14 10 40](https://user-images.githubusercontent.com/2078984/36651807-d7945b1c-1afe-11e8-9a0a-ca488e4415d2.jpg)

**Comment by RobbieFerguson** [comment]
Hey! Thanks for your feedback. Unfortunately this bug bounty is purely for bugs within the solidity contract. Feel free to post this in the Discord for UI/UX feedback.
