### ISSUE TITLE
In order for EVM to optimize the read write of storage, pack variables as tightly as possible.

### ISSUE THREAD

**Issue by jsdu** [EtherBots/ETHERBOTS-Bug-Bounty#22]
http://solidity.readthedocs.io/en/develop/miscellaneous.html

This can be seen in struct Part.
struct Part {
        uint32 tokenId; 
        uint8 partType;
        uint8 partSubType;
        uint8 rarity;
        uint8 element;
        uint32 battlesLastDay;
        uint32 experience;
        uint32 forgeTime; // TODO: check whether we need uint64
        uint32 battlesLastReset;
}

tokenId should be next to battlesLastDay in order to save on gas.

**Comment by RobbieFerguson** [comment]
The whole thing packs into bytes32 so it doesn't make a difference :) but thanks!
