### ISSUE TITLE
addExperience seems to have no validation

### ISSUE THREAD

**Issue by dylanjsa** [EtherBots/ETHERBOTS-Bug-Bounty#23]
Hi,

I'm having a look at EtherbotsBattle.sol::addExperience. The only real validation I see is that the battles should be approved and that partIds and _exps should match in length.

The amount of exp to add doesn't seem to be validate - this method is external which should mean that any user can add any chosen amount of xp - as long as the battle was valid.

**Comment by RobbieFerguson** [comment]
Only the battle contract can call this. :)
