### ISSUE TITLE
Incorrectly using parts.length as the new part id

### ISSUE THREAD

**Issue by BobbyMcWho** [EtherBots/ETHERBOTS-Bug-Bounty#24]
Throughout the contracts you store parts in an array `parts`. Since you are using an array, this is a 0 based indexed list. In the forge when you create a part, you set the id to be equal to [parts.length.](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/PerksRewards.sol#L11) , while in other places such as the experience awards you add experience to the part in the `part[_id]` index. Because an array always has `length - 1` indices, this is awarding experience incorrectly to the part one index after the part that _should_ have the experience awarded. 

Ex: With 99 parts in existence, creating a new part would give it the tokenId 100, but parts[100] would not return an existing part. 

Places where this issue exists:
[Base.sol#L153](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/Base.sol#L153)
[ERC721.sol#338](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/ERC721.sol#L338)
[ERC721.sol#397](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/ERC721.sol#L397)
[EtherbotsBattle.sol#L229](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/EtherbotsBattle.sol#L249)
[EtherbotsBattle.sol#L229](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/EtherbotsBattle.sol#L249) (2x)
[EtherbotsBattle.sol#L268](https://github.com/EtherBots/ETHERBOTS-Bug-Bounty/blob/master/EtherbotsBattle.sol#L268)

Likelihood: High
Impact: High

Ethereum Address: 0x3D9317cC2e741794C8b53E175e2C1e28170F6e18

**Comment by RobbieFerguson** [comment]
Hey, the function is a little bit confusingly written which is probably why you thought this. We actually set the token ID to parts.length _before_ pushing the new part. 
So with 99 parts in existence, the 99th part has token ID 98. The 100th token would have tokenID 99. Token IDs are a direct index into the corresponding part in the parts array.

No issue here, but thank you! We need more eyes on these high-security area of the contract.
